<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('employees')->delete();
        
        \DB::table('employees')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Md Abdullah',
                'address' => 'Pirojpur',
                'mobile_no' => '01779439274',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 50000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-05 23:17:36',
                'updated_at' => '2025-07-22 18:17:07',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Md Farhad',
                'address' => 'Kishorganj',
                'mobile_no' => '01717719522',
                'mobile_no_two' => NULL,
                'image' => '67fded84d39d4.jpg',
                'limit' => 50000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:24:21',
                'updated_at' => '2025-04-16 01:05:22',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Md Kamal',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01837514568',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 100000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:25:12',
                'updated_at' => '2025-09-28 12:18:44',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Md Musa Mia',
                'address' => 'Bhairab Bazar',
                'mobile_no' => '01861586199',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 200000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:26:27',
                'updated_at' => '2025-08-12 10:52:37',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Md Khokon',
                'address' => 'Kishoreganj',
                'mobile_no' => '01734338446',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 60000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:27:48',
                'updated_at' => '2025-08-12 10:53:19',
            ),
            5 => 
            array (
                'id' => 6,
            'name' => 'Md Shiful Azam (Rasal)',
                'address' => 'Comilla',
                'mobile_no' => '01790641410',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 200000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:29:29',
                'updated_at' => '2025-08-12 10:58:48',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Md Shah Poran',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01880358680',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 70000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:31:33',
                'updated_at' => '2025-08-12 10:49:04',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Md Rasel',
                'address' => 'Kishoreganj',
                'mobile_no' => '01750329930',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 150000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:33:08',
                'updated_at' => '2025-09-25 16:03:57',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Md Wahid',
                'address' => 'Savar, Dhaka',
                'mobile_no' => '01333372533',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 25000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:33:44',
                'updated_at' => '2025-07-22 18:22:57',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Md Hasan',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01825935276',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 100000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:36:00',
                'updated_at' => '2025-08-12 10:51:30',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Md Mehedi',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01319565437',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 50000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:37:16',
                'updated_at' => '2025-08-12 11:01:24',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Md Junnun',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01610149450',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 80000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:37:53',
                'updated_at' => '2025-08-12 10:57:55',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Md Shamim',
                'address' => 'Brahmanbaria',
                'mobile_no' => '01409448543',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 70000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:39:00',
                'updated_at' => '2025-08-12 10:57:19',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Md Masud',
                'address' => 'Chandpur',
                'mobile_no' => '01620254116',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 60000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:40:54',
                'updated_at' => '2025-08-12 10:56:29',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Md Anis Mia',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01603075639',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 10000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:41:30',
                'updated_at' => '2025-07-22 18:24:25',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Md Harun',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01611031650',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 50000.0,
                'salary' => NULL,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:42:02',
                'updated_at' => '2025-08-12 10:54:36',
            ),
            16 => 
            array (
                'id' => 17,
            'name' => 'Md Jahangir (Driver)',
                'address' => 'Dhaka',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 10000.0,
                'salary' => 17000.0,
                'join_date' => '2025-04-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-15 17:44:44',
                'updated_at' => '2025-10-22 16:06:18',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Md Mahfuz',
                'address' => 'Comilla',
                'mobile_no' => '01811568191',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 50000.0,
                'salary' => NULL,
                'join_date' => '2024-08-12',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-16 01:11:03',
                'updated_at' => '2025-08-12 10:55:57',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Md. Sadrul',
                'address' => 'Rangpur',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-05-03 00:02:25',
                'updated_at' => '2025-05-03 00:02:25',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Md Saleman',
                'address' => 'Murad Nagar',
                'mobile_no' => '01983923066',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 5000.0,
                'salary' => NULL,
                'join_date' => '2025-05-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-05-27 16:17:27',
                'updated_at' => '2025-07-24 12:20:16',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Md Prince',
                'address' => 'Murad Nagar',
                'mobile_no' => '01825002808',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-05-27 16:18:48',
                'updated_at' => '2025-07-22 18:22:26',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Md Ripon',
                'address' => 'Mymensingh',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 20000.0,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-08-13 12:29:02',
                'updated_at' => '2026-01-29 18:07:50',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Md Mahir',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 20000.0,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-08-13 14:24:47',
                'updated_at' => '2026-01-29 18:07:18',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Md Sunny',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 20000.0,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-08-13 15:16:38',
                'updated_at' => '2026-01-29 18:07:09',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Md Abu Bakkar',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 20000.0,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-08-30 10:55:57',
                'updated_at' => '2026-01-29 18:07:01',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Md Parvez',
                'address' => 'Muradnagar, Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => 20000.0,
                'salary' => NULL,
                'join_date' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-08-30 10:56:44',
                'updated_at' => '2026-01-29 18:06:52',
            ),
            26 => 
            array (
                'id' => 27,
            'name' => 'Mahfujur Rahman (Antor)',
                'address' => 'Pathantoli, Narayanganj',
                'mobile_no' => '01926271512',
                'mobile_no_two' => NULL,
                'image' => '6933c41a26730.jpeg',
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2025-11-18',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-01 17:16:20',
                'updated_at' => '2025-12-06 11:50:18',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Md Sagor',
                'address' => 'Sirajganj',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => '6933bee753c64.jpg',
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2025-10-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-06 11:28:07',
                'updated_at' => '2025-12-06 11:28:07',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Md Sajid',
                'address' => 'Dhaka',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => '6933bf4246be2.JPG',
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2025-10-01',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-12-06 11:29:39',
                'updated_at' => '2025-12-06 11:29:39',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Rabbi',
                'address' => 'Dhaka',
                'mobile_no' => '*******',
                'mobile_no_two' => NULL,
                'image' => '697d9c5b8c98d.jpeg',
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2026-01-26',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-31 12:08:27',
                'updated_at' => '2026-01-31 12:09:43',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Sakibul',
                'address' => 'Dhaka',
                'mobile_no' => '000000',
                'mobile_no_two' => NULL,
                'image' => '697d9cd1b6d15.jpeg',
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2026-01-26',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-31 12:10:25',
                'updated_at' => '2026-01-31 12:10:25',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Md Rabbi',
                'address' => 'Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2026-01-24',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-03-16 03:07:03',
                'updated_at' => '2026-03-16 03:07:03',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Md Akib',
                'address' => 'Comilla',
                'mobile_no' => '01',
                'mobile_no_two' => NULL,
                'image' => NULL,
                'limit' => NULL,
                'salary' => NULL,
                'join_date' => '2026-01-17',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-03-16 03:09:43',
                'updated_at' => '2026-03-16 03:09:43',
            ),
        ));
        
        
    }
}