<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeeSalariesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('employee_salaries')->delete();
        
        \DB::table('employee_salaries')->insertOrIgnore(array (
            0 => 
            array (
                'id' => 1,
                'employee_id' => 2,
                'account_book_id' => 185,
                'salary' => '13500.00',
                'limit' => '25000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-11-10 13:43:27',
                'updated_at' => '2025-12-01 18:10:30',
            ),
            1 => 
            array (
                'id' => 2,
                'employee_id' => 17,
                'account_book_id' => 200,
                'salary' => '18000.00',
                'limit' => '20000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-11-30 14:16:24',
                'updated_at' => '2026-03-08 14:50:37',
            ),
            2 => 
            array (
                'id' => 3,
                'employee_id' => 1,
                'account_book_id' => 15,
                'salary' => '10000.00',
                'limit' => '30000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 14:47:56',
                'updated_at' => '2025-12-01 16:16:32',
            ),
            3 => 
            array (
                'id' => 4,
                'employee_id' => 8,
                'account_book_id' => 191,
                'salary' => '10000.00',
                'limit' => '25000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 14:48:59',
                'updated_at' => '2026-03-16 13:11:30',
            ),
            4 => 
            array (
                'id' => 5,
                'employee_id' => 10,
                'account_book_id' => 193,
                'salary' => '15000.00',
                'limit' => '15000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 16:02:50',
                'updated_at' => '2025-12-01 16:02:50',
            ),
            5 => 
            array (
                'id' => 6,
                'employee_id' => 12,
                'account_book_id' => 195,
                'salary' => '0.00',
                'limit' => '15000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 16:04:51',
                'updated_at' => '2025-12-01 16:04:51',
            ),
            6 => 
            array (
                'id' => 7,
                'employee_id' => 9,
                'account_book_id' => 192,
                'salary' => '22000.00',
                'limit' => '22000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 17:00:44',
                'updated_at' => '2025-12-01 17:00:44',
            ),
            7 => 
            array (
                'id' => 8,
                'employee_id' => 27,
                'account_book_id' => 1227,
                'salary' => '19000.00',
                'limit' => '30000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-11-18',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 17:16:44',
                'updated_at' => '2026-03-08 13:12:05',
            ),
            8 => 
            array (
                'id' => 9,
                'employee_id' => 7,
                'account_book_id' => 190,
                'salary' => '0.00',
                'limit' => '35000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 18:09:25',
                'updated_at' => '2026-03-16 13:08:48',
            ),
            9 => 
            array (
                'id' => 10,
                'employee_id' => 6,
                'account_book_id' => 189,
                'salary' => '0.00',
                'limit' => '50000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 18:09:36',
                'updated_at' => '2025-12-01 18:09:36',
            ),
            10 => 
            array (
                'id' => 11,
                'employee_id' => 5,
                'account_book_id' => 188,
                'salary' => '0.00',
                'limit' => '50000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 18:09:48',
                'updated_at' => '2025-12-01 18:09:48',
            ),
            11 => 
            array (
                'id' => 12,
                'employee_id' => 4,
                'account_book_id' => 187,
                'salary' => '0.00',
                'limit' => '40000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 18:10:00',
                'updated_at' => '2025-12-01 18:10:00',
            ),
            12 => 
            array (
                'id' => 13,
                'employee_id' => 3,
                'account_book_id' => 186,
                'salary' => '0.00',
                'limit' => '40000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-01 18:10:11',
                'updated_at' => '2025-12-01 18:10:11',
            ),
            13 => 
            array (
                'id' => 14,
                'employee_id' => 14,
                'account_book_id' => 197,
                'salary' => '0.00',
                'limit' => '23000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:26:22',
                'updated_at' => '2026-03-16 13:13:16',
            ),
            14 => 
            array (
                'id' => 15,
                'employee_id' => 11,
                'account_book_id' => 194,
                'salary' => '0.00',
                'limit' => '15000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:33:32',
                'updated_at' => '2025-12-06 11:33:32',
            ),
            15 => 
            array (
                'id' => 16,
                'employee_id' => 20,
                'account_book_id' => 1077,
                'salary' => '0.00',
                'limit' => '17000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-05-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:34:50',
                'updated_at' => '2025-12-06 11:34:50',
            ),
            16 => 
            array (
                'id' => 17,
                'employee_id' => 29,
                'account_book_id' => 1233,
                'salary' => '0.00',
                'limit' => '16000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-10-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:39:40',
                'updated_at' => '2025-12-06 11:39:40',
            ),
            17 => 
            array (
                'id' => 18,
                'employee_id' => 28,
                'account_book_id' => 1232,
                'salary' => '0.00',
                'limit' => '25000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-10-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:40:48',
                'updated_at' => '2026-03-08 13:09:32',
            ),
            18 => 
            array (
                'id' => 19,
                'employee_id' => 15,
                'account_book_id' => 198,
                'salary' => '0.00',
                'limit' => '20000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-06 11:53:51',
                'updated_at' => '2025-12-06 11:53:51',
            ),
            19 => 
            array (
                'id' => 20,
                'employee_id' => 16,
                'account_book_id' => 199,
                'salary' => '0.00',
                'limit' => '10000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-07 12:12:05',
                'updated_at' => '2025-12-07 12:12:05',
            ),
            20 => 
            array (
                'id' => 21,
                'employee_id' => 19,
                'account_book_id' => 405,
                'salary' => '0.00',
                'limit' => '30000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2025-12-30 16:15:39',
                'updated_at' => '2025-12-30 16:15:39',
            ),
            21 => 
            array (
                'id' => 22,
                'employee_id' => 23,
                'account_book_id' => 1144,
                'salary' => '15000.00',
                'limit' => '10000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-07-30',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-01-11 17:32:39',
                'updated_at' => '2026-01-11 17:32:39',
            ),
            22 => 
            array (
                'id' => 23,
                'employee_id' => 26,
                'account_book_id' => 1151,
                'salary' => '10000.00',
                'limit' => '10000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-08-25',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-01-11 17:33:28',
                'updated_at' => '2026-01-11 17:33:28',
            ),
            23 => 
            array (
                'id' => 24,
                'employee_id' => 30,
                'account_book_id' => 1269,
                'salary' => '0.00',
                'limit' => '15000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2026-01-26',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-01-31 12:09:15',
                'updated_at' => '2026-04-05 12:28:45',
            ),
            24 => 
            array (
                'id' => 25,
                'employee_id' => 31,
                'account_book_id' => 1270,
                'salary' => '0.00',
                'limit' => '30000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2026-01-26',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-01-31 12:10:36',
                'updated_at' => '2026-04-05 12:30:57',
            ),
            25 => 
            array (
                'id' => 26,
                'employee_id' => 18,
                'account_book_id' => 387,
                'salary' => '0.00',
                'limit' => '30000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2025-04-01',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-04-05 12:21:54',
                'updated_at' => '2026-04-05 12:21:54',
            ),
            26 => 
            array (
                'id' => 27,
                'employee_id' => 33,
                'account_book_id' => 1385,
                'salary' => '0.00',
                'limit' => '15000.00',
                'previous_debt' => '0.00',
                'previous_creadit' => '0.00',
                'remarks' => NULL,
                'salary_start_date' => '2026-01-17',
                'previous_salary' => NULL,
                'salary_change' => NULL,
                'created_at' => '2026-04-05 12:29:41',
                'updated_at' => '2026-04-05 12:29:41',
            ),
        ));
        
        
    }
}